name: 🔨 Staging Deployment
on:
  push:
    branches: [ v2 ]
jobs:
  build:
    name: 🔨 Staging
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 358038.w38.wedos.net
          username: w358038
          password: i_Maiden_37
          protocol: ftp
          server-dir: www/projects/grip/
          exclude: |
            **/.git*
            **/.git*/**
