name: 🔨 Staging Deployment
on:
  push:
    branches: [ v2 ]
jobs:
  build:
    name: 🔨 Staging
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 62.109.154.228
          username: grip.endora.site
          password: EeQeknsn2
          protocol: ftp
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
